# the next 3 are requirements for multi-CPI BOSH Directors like mine
- type: replace
  path: /azs/name=z1/cpi?
  value: vsphere

- type: replace
  path: /azs/name=z2/cpi?
  value: vsphere

- type: replace
  path: /azs/name=z3/cpi?
  value: vsphere

# fixes "Error: Cloud config 'compilation' key cannot be defined in multiple cloud configs."
- type: remove
  path: /compilation

# We only use one AZ; delete z2 & z3 and their subnets
- type: remove
  path: /azs/name=z2

- type: remove
  path: /azs/name=z3

- type: remove
  path: /networks/name=default/subnets/az=z2

- type: remove
  path: /networks/name=default/subnets/az=z3

# fixes "Error: Duplicate vm type name 'small'"
- type: remove
  path: /vm_types/name=small

# fixes "Error: Instance group 'haproxy' with network 'default' declares static ip '10.0.250.10', which belongs to no subnet"
- type: replace
  path: /networks/name=default/subnets/az=z1/static?
  value: [10.0.250.10]

# IPv6 network for HA Proxy
- type: replace
  path: /networks/name=PAS-IPv6?
  value:
    name: PAS-IPv6
    subnets:
    - az: z1
      cloud_properties:
        name: cf
      dns:
      - 2601:646:100:69f5:0000:0000:0000:0000
      gateway: 2601:646:100:69f5:20d:b9ff:fe48:9249
      range: 2601:0646:0100:69f5:0000:0000:0000:0000/64
      reserved:
      - 2601:646:100:69f5:20d:b9ff:fe48:9249
      static:
      - 2601:0646:0100:69f5:0000:0000:0000:0010
